require("felix.core.options")
require("felix.core.keymaps")
require("felix.core.colorscheme")
require("felix.plugins-setup")
require("felix.plugins.comment")
require("felix.plugins.nvim-tree")
require("felix.plugins.lualine")
require("felix.plugins.telescope")
require("felix.plugins.nvim-cmp")
require("felix.plugins.lsp.lspsaga")
require("felix.plugins.lsp.mason")
require("felix.plugins.lsp.lspconfig")
require("felix.plugins.lsp.null-ls")
require("felix.plugins.autopairs")
require("felix.plugins.treesitter")
require("felix.plugins.gitsigns")
require("felix.plugins.tabout")

